/* Shared interactions for the EdgeCenter concept. All demos are local. */
(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const base=document.body.dataset.base||'./';
const plural=(n,one,few,many)=>{const a=n%100,b=n%10;return a>=11&&a<=14?many:b===1?one:b>=2&&b<=4?few:many;};
window.lucide?.createIcons({attrs:{'aria-hidden':'true',focusable:'false'}});
const menu=$('.ec-menu-trigger'),panel=$('#ec-products-panel'),mobile=$('.ec-mobile'),nav=$('#ec-nav');
function closeProducts(){menu.setAttribute('aria-expanded','false');panel.hidden=true;}
function closeMobile(){mobile.setAttribute('aria-expanded','false');mobile.setAttribute('aria-label','Открыть меню');nav.classList.remove('is-open');closeProducts();}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));panel.hidden=open;});
mobile.addEventListener('click',()=>{const open=mobile.getAttribute('aria-expanded')==='true';mobile.setAttribute('aria-expanded',String(!open));mobile.setAttribute('aria-label',open?'Открыть меню':'Закрыть меню');nav.classList.toggle('is-open',!open);if(open)closeProducts();});
document.addEventListener('click',e=>{if(!e.target.closest('.ec-products'))closeProducts();if(!e.target.closest('.ec-header'))closeMobile();});
$('.ec-products').addEventListener('focusout',e=>{if(!e.currentTarget.contains(e.relatedTarget))closeProducts();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')){if(!panel.hidden){closeProducts();menu.focus();}else if(nav.classList.contains('is-open')){closeMobile();mobile.focus();}}});
$$('a',nav).forEach(a=>a.addEventListener('click',closeMobile));
const contact=$('.ec-contact'),form=$('#ec-contact-form'),result=$('#ec-contact-result');let contactTrigger;
function showContact(trigger,topic,message=''){
 contactTrigger=trigger;closeMobile();form.hidden=false;result.hidden=true;
 form.elements.subject.value=topic||$('h1')?.innerText.replace(/\n/g,' ')||'Обсудить проект';
 form.elements.message.value=message;contact.showModal();
}
$$('[data-contact]').forEach(b=>b.addEventListener('click',()=>showContact(b,b.dataset.topic||(b.closest('.task-description')?document.querySelector('[data-task][aria-selected=true]')?.textContent.trim():null)||document.title.replace(' — edge_center',''))));
$('.ec-dialog-close').addEventListener('click',()=>contact.close());
function backdropClose(dialog){dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});}
backdropClose(contact);contact.addEventListener('close',()=>contactTrigger?.focus());
form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);const text=`Здравствуйте!\n\nТема: ${d.get('subject')}\n\n${d.get('message')}\n\n${d.get('name')}\n${d.get('email')}`;$('#ec-request-text').textContent=text;$('#ec-mailto').href='mailto:sales@edgecenter.ru?subject='+encodeURIComponent(d.get('subject'))+'&body='+encodeURIComponent(text);form.hidden=true;result.hidden=false;$('#ec-mailto').focus();});
$('#ec-edit').addEventListener('click',()=>{form.hidden=false;result.hidden=true;form.elements.message.focus();});
const pages=[['products','Все продукты','Экосистема'],['cloud','Облачная инфраструктура','Вычисления'],['kubernetes','Managed Kubernetes','Вычисления'],['hosting','Хостинг и серверы','Вычисления'],['cdn','Сеть доставки контента CDN','Доставка'],['storage','Объектное хранилище S3','Вычисления'],['security','Защита DDoS, WAF, антибот','Безопасность'],['dns','DNS-хостинг','Сеть'],['streaming-platform','Стриминговая платформа','Видео'],['qa','QA-центр','Экспертиза'],['it-management','Управление IT-инфраструктурой','Экспертиза'],['solutions','Решения для бизнеса','Решения'],['online-retail','Онлайн-ритейл','Решения'],['games','Игры','Решения'],['media','Медиа','Решения'],['fintech','Финтех','Решения'],['education','Образование','Решения'],['saas','SaaS','Решения'],['pricing','Тарифы','Условия'],['developers','Разработчикам и база знаний','Документация'],['blog','Блог','Материалы'],['about','О компании','Компания'],['contacts','Контакты','Компания']];
const searchAliases={cloud:'облако облака сервер cloud',kubernetes:'кубернетес кубер k8s контейнеры',storage:'хранение файлов s3 бакет',security:'безопасность ддос антиддос waf anti-bot',cdn:'цдн кэш кеш ускорение контент',hosting:'vps vds dedicated сервер',dns:'днс домен','streaming-platform':'стрим видео трансляция',qa:'тестирование качество','it-management':'администрирование мониторинг'};
const search=$('.ec-search'),searchInput=$('#ec-search-input'),searchResults=$('#ec-search-results');let searchTrigger;
function renderSearch(){const q=searchInput.value.trim().toLocaleLowerCase('ru');const found=pages.filter(p=>(p.join(' ')+' '+(searchAliases[p[0]]||'')).toLocaleLowerCase('ru').includes(q));searchResults.replaceChildren();for(const [slug,title,group] of found){const a=document.createElement('a');a.href=base+slug+'/';const t=document.createElement('span'),g=document.createElement('small');t.textContent=title;g.textContent=group+' ↗';a.append(t,g);searchResults.append(a);}if(!found.length){const p=document.createElement('p');p.textContent='Ничего не найдено. Попробуйте название продукта или раздела.';searchResults.append(p);}}
function openSearch(trigger){searchTrigger=trigger;closeMobile();renderSearch();search.showModal();searchInput.focus();}
$('.ec-search-trigger').addEventListener('click',e=>openSearch(e.currentTarget));$('.ec-search-close').addEventListener('click',()=>search.close());backdropClose(search);search.addEventListener('close',()=>searchTrigger?.focus());searchInput.addEventListener('input',renderSearch);
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){if(document.querySelector('dialog[open]'))return;e.preventDefault();openSearch($('.ec-search-trigger'));}});
$$('[data-audience]').forEach(b=>b.addEventListener('click',()=>{const card=b.closest('.audience-card'),copy=$('[data-audience-copy]',card);$$('[data-audience]',card).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));copy.textContent=copy.dataset[b.dataset.audience];}));
const config=$('[data-demo=config]');if(config){const inputs=$$('input[type=range]',config),presets={start:[4,8,80],app:[8,32,200],scale:[16,64,500]};function update(){const [cpu,ram,disk]=inputs.map(i=>i.value);$('#cpu-out').textContent=cpu+' vCPU';$('#ram-out').textContent=ram+' ГБ';$('#disk-out').textContent=disk+' ГБ';$('#config-summary').innerHTML=cpu+' vCPU<br><em>'+ram+' ГБ RAM</em>';$('#config-disk').textContent=disk+' ГБ SSD';}inputs.forEach(i=>i.addEventListener('input',()=>{$$('[data-preset]',config).forEach(b=>b.setAttribute('aria-pressed','false'));update();}));$$('[data-preset]',config).forEach(b=>b.addEventListener('click',()=>{inputs.forEach((i,n)=>i.value=presets[b.dataset.preset][n]);$$('[data-preset]',config).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));update();}));$('[data-config-contact]').addEventListener('click',e=>showContact(e.currentTarget,'Расчёт: '+document.title.replace(' — edge_center',''),`Нужна конфигурация: ${inputs[0].value} vCPU, ${inputs[1].value} ГБ RAM, ${inputs[2].value} ГБ SSD.\n\nЗадача проекта: `));}
const network=$('[data-demo=network]');if(network){$$('[data-network]',network).forEach(b=>b.addEventListener('click',()=>{network.dataset.mode=b.dataset.network;$$('[data-network]',network).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('.demo-explanation',network).textContent=b.dataset.network==='cdn'?'Повторные запросы обслуживаются в сети CDN. Источник получает меньше обращений.':'Каждый запрос за контентом приходит напрямую к источнику. Кэширование в сети CDN не используется.';}));}
const security=$('[data-demo=security]');if(security){$$('.packet',security).forEach((p,i)=>{p.style.setProperty('--row',i%6);p.style.setProperty('--col',Math.floor(i/6));});$$('[data-protection]',security).forEach(b=>b.addEventListener('click',()=>{security.dataset.mode=b.dataset.protection;$$('[data-protection]',security).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('.demo-explanation',security).textContent=b.dataset.protection==='attack'?'Красные запросы обозначают угрозы: защитный контур отфильтровывает их. Пользовательский трафик проходит к приложению.':'Пользовательские запросы проходят через защитный контур к приложению.';}));}
const storage=$('[data-demo=storage]');if(storage){const input=$('input',storage),select=$('select',storage),rows=$$('[data-object]',storage);function filter(){let count=0;for(const row of rows){const show=row.dataset.object.toLowerCase().includes(input.value.toLowerCase().trim())&&(select.value==='Все файлы'||row.dataset.type===select.value);row.hidden=!show;if(show)count++;}$('.object-empty',storage).hidden=count>0;$('#object-count').textContent=count+' '+plural(count,'объект','объекта','объектов')+' · демонстрационные данные';}input.addEventListener('input',filter);select.addEventListener('change',filter);}
let toastTimer;function toast(message){let el=$('.copy-toast');if(!el){el=document.createElement('div');el.className='copy-toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.remove(),3000);}
const dns=$('[data-demo=dns]');if(dns){const records={A:['www','192.0.2.10','A-запись связывает имя с IPv4-адресом.'],AAAA:['www','2001:db8::10','AAAA-запись связывает имя с IPv6-адресом.'],CNAME:['cdn','edge.example.com.','CNAME задаёт псевдоним для другого доменного имени.'],MX:['@','10 mail.example.com.','MX указывает почтовый сервер и его приоритет.']};$$('[data-dns]',dns).forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.dns,[name,value,desc]=records[type];$$('[data-dns]',dns).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#dns-name').textContent=name;$('#dns-type').textContent=type;$('#dns-value').textContent=value;$('#dns-code').textContent=(name==='@'?'example.com.':name+'.example.com.')+' 300 IN '+type+' '+value;$('.demo-explanation',dns).textContent=desc;}));$('[data-copy-dns]').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#dns-code').textContent);toast('Пример записи скопирован');}catch{toast('Выделите запись и скопируйте её вручную');}});}
const cluster=$('[data-demo=cluster]');if(cluster){const descriptions={ingress:'Ingress направляет входящие запросы к нужным сервисам приложения.',services:'Сервисы приложения работают в контейнерах и обмениваются данными внутри архитектуры.',data:'Слой данных обеспечивает хранение информации, которую использует приложение.'};$$('[data-layer]',cluster).forEach(b=>b.addEventListener('click',()=>{$$('[data-layer]',cluster).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('.demo-explanation',cluster).textContent=descriptions[b.dataset.layer];}));}
const qa=$('[data-demo=qa]');if(qa){$$('input',qa).forEach(x=>x.addEventListener('change',()=>{const n=$$('input:checked',qa).length;$('#qa-count').textContent=n+' из 4';$('#qa-bar').style.width=(n*25)+'%';$('.demo-explanation',qa).textContent=n===4?'Все этапы примера отмечены. Реальный план и результат проверки согласуются с командой.':'Отмечено этапов: '+n+'. Продолжите проверку по чек-листу.';}));}
const catalog=$('[data-catalog]');if(catalog){let category='Все продукты';const input=$('input',catalog),cards=$$('.ec-product-card',catalog);function filter(){let count=0;for(const c of cards){const match=(category==='Все продукты'||category===c.dataset.category)&&c.dataset.search.toLowerCase().includes(input.value.trim().toLowerCase());c.hidden=!match;if(match)count++;}$('.filter-result',catalog).textContent=count+' '+plural(count,'продукт','продукта','продуктов');$('.catalog-empty',catalog).hidden=count>0;}input.addEventListener('input',filter);$$('[data-filter]',catalog).forEach(b=>b.addEventListener('click',()=>{category=b.dataset.filter;$$('[data-filter]',catalog).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filter();}));}
const blog=$('[data-blog]');if(blog){$$('[data-blog-filter]',blog).forEach(b=>b.addEventListener('click',()=>{let count=0;$$('[data-blog-filter]',blog).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$$('.blog-card',blog).forEach(c=>{c.hidden=b.dataset.blogFilter!=='Все'&&c.dataset.topic!==b.dataset.blogFilter;if(!c.hidden)count++;});$('.blog-count',blog).textContent=count+' '+plural(count,'материал','материала','материалов');}));}
if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches){$$('.glow-card').forEach(c=>{let raf=0,x=0,y=0;c.addEventListener('pointermove',e=>{const r=c.getBoundingClientRect();x=e.clientX-r.left;y=e.clientY-r.top;if(!raf)raf=requestAnimationFrame(()=>{c.style.setProperty('--mx',x+'px');c.style.setProperty('--my',y+'px');raf=0;});});});}
// A local light spot makes the material respond to the pointer; no idle animation.
if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches){
 $$('.v2-pillar').forEach(card=>{let raf=0,x=50,y=35;card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();x=(e.clientX-r.left)/r.width*100;y=(e.clientY-r.top)/r.height*100;if(!raf)raf=requestAnimationFrame(()=>{card.style.setProperty('--spot-x',x+'%');card.style.setProperty('--spot-y',y+'%');raf=0;});},{passive:true});card.addEventListener('pointerleave',()=>{cancelAnimationFrame(raf);raf=0;card.style.removeProperty('--spot-x');card.style.removeProperty('--spot-y');},{passive:true});});
}
// Diagram animation follows viewport visibility, document visibility and an explicit pause control.
const reduced=matchMedia('(prefers-reduced-motion:reduce)');
$$('.network-demo,.security-demo').forEach(demo=>{
 let inView=false,paused=reduced.matches;
 const button=document.createElement('button');button.className='diagram-motion';button.setAttribute('aria-pressed',String(paused));
 function update(){button.textContent=paused?'Включить движение':'Пауза движения';button.setAttribute('aria-pressed',String(paused));$$('.path-flow,.packet',demo).forEach(el=>el.style.animationPlayState=inView&&!document.hidden&&!reduced.matches&&!paused?'running':'paused');}
 button.addEventListener('click',()=>{paused=!paused;update();});$('.console-bar',demo).append(button);
 const observer=new IntersectionObserver(([e])=>{inView=e.isIntersecting;update();},{threshold:.1});observer.observe(demo);
 document.addEventListener('visibilitychange',update);reduced.addEventListener('change',()=>{paused=reduced.matches;update();});update();
});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const open=document.querySelector('dialog[open]');if(open){e.preventDefault();open.close();}}},true);
const intro=$('.intro-dialog');if(intro){const video=$('#intro-video');let trigger;$$('[data-intro]').forEach(b=>b.addEventListener('click',()=>{trigger=b;intro.showModal();if(video.ended)video.currentTime=0;video.play().catch(()=>{});}));$('.intro-close').addEventListener('click',()=>intro.close());backdropClose(intro);intro.addEventListener('close',()=>{video.pause();trigger?.focus();});}
})();
