from pathlib import Path
import json,re,html,sys
from content import PRODUCTS,SOLUTIONS
ROOT=Path(__file__).resolve().parent.parent
P={p['slug']:p for p in PRODUCTS}
E=html.escape
icons=lambda n:f'<i data-lucide="{n}" aria-hidden="true"></i>'
A=icons('arrow-up-right')
def link(slug):return slug+'/' if slug else './'
def header(base,current=''):
 groups=''
 for group in ['Вычисления','Сеть и доставка','Безопасность','Экспертиза']:
  groups+=f'<div class="ec-menu-group"><span>{group}</span>'+''.join(f'<a href="{base}{p["slug"]}/">{icons(p["icon"])}<span>{p["short"]}</span>{A}</a>' for p in PRODUCTS if p['group']==group)+'</div>'
 return f'''<a class="skip" href="#main">Перейти к содержимому</a><header class="ec-header"><div class="ec-header-inner"><a class="brand" href="{base}" aria-label="edge_center — на главную"><img src="{base}assets/edge-center-logo.png" alt="edge_center" width="1126" height="227"></a><nav class="ec-nav" id="ec-nav" aria-label="Основная навигация"><div class="ec-products"><button class="ec-menu-trigger" aria-expanded="false" aria-controls="ec-products-panel">Продукты {icons('chevron-down')}</button><div id="ec-products-panel" class="ec-products-panel" hidden><div class="ec-menu-top"><span class="eyebrow">Одна экосистема. Все возможности.</span><a href="{base}products/">Все продукты {A}</a></div><div class="ec-menu-grid">{groups}</div></div></div><a href="{base}solutions/" {'aria-current="page"' if current=='solutions' else ''}>Решения</a><a href="{base}pricing/" {'aria-current="page"' if current=='pricing' else ''}>Тарифы</a><a href="{base}developers/" {'aria-current="page"' if current=='developers' else ''}>Разработчикам</a><a href="{base}about/" {'aria-current="page"' if current=='about' else ''}>Компания</a></nav><div class="ec-header-actions"><button class="ec-search-trigger" aria-label="Найти продукт" aria-haspopup="dialog">{icons('search')}</button><a class="ec-login" href="https://auth.edgecenter.ru/login/signin">Войти {A}</a><button class="button button-sm" data-contact>Обсудить проект</button><button class="ec-mobile" aria-label="Открыть меню" aria-expanded="false" aria-controls="ec-nav">{icons('menu')}</button></div></div></header>'''
def footer(base):
 return f'''<footer class="ec-footer"><div class="wrap"><div class="ec-footer-intro"><a class="brand" href="{base}" aria-label="edge_center — на главную"><img src="{base}assets/edge-center-logo.png" alt="edge_center" width="1126" height="227"></a><p>В основе того,<br>что вы создадите дальше.</p><a href="tel:88007750854">8 800 775 08 54</a></div><div class="ec-footer-grid"><div><h3>Продукты</h3>{''.join(f'<a href="{base}{p["slug"]}/">{p["short"]}</a>' for p in PRODUCTS[:5])}</div><div><h3>Платформа</h3>{''.join(f'<a href="{base}{p["slug"]}/">{p["short"]}</a>' for p in PRODUCTS[5:])}</div><div><h3>Решения</h3>{''.join(f'<a href="{base}{s[0]}/">{s[1]}</a>' for s in SOLUTIONS)}</div><div><h3>Компания</h3><a href="{base}about/">О компании</a><a href="{base}blog/">Блог</a><a href="{base}contacts/">Контакты</a><a href="{base}developers/">Разработчикам</a><a href="{base}pricing/">Тарифы</a><a href="{base}downloads/edge-center-brandbook.pdf" target="_blank" rel="noopener">Брендбук · PDF {A}</a></div><div><h3>Всегда рядом</h3><a href="mailto:sales@edgecenter.ru">sales@edgecenter.ru {A}</a><a href="mailto:support@edgecenter.ru">support@edgecenter.ru {A}</a><a href="https://status.edgecenter.ru/">Статус сервисов {A}</a><a href="https://t.me/edgecenter_news">Telegram {A}</a><button class="text-link" data-contact>Задать вопрос {A}</button></div></div><div class="ec-footer-bottom"><span>© 2026 edge_center · Дизайн-концепт</span><a href="https://edgecenter.ru/legal/pd-processing-policy">Политика конфиденциальности {A}</a><a href="#">Наверх {icons('arrow-up')}</a></div></div></footer>'''
def dialogs(base):
 return f'''<dialog class="ec-contact" aria-labelledby="ec-contact-title"><button class="ec-dialog-close" aria-label="Закрыть окно">{icons('x')}</button><span class="eyebrow">Начнём с вашей задачи</span><h2 id="ec-contact-title">Дайте идее<br><em>сильную основу.</em></h2><form id="ec-contact-form"><div class="ec-form-row"><label>Ваше имя<input name="name" autocomplete="name" required placeholder="Как к вам обращаться"></label><label>Рабочая почта<input type="email" name="email" autocomplete="email" required placeholder="you@company.ru"></label></div><label>Тема<input name="subject" required></label><label>О проекте<textarea name="message" rows="4" required placeholder="Что хотите запустить, улучшить или защитить?"></textarea></label><button class="button" type="submit">Подготовить обращение {A}</button><p class="ec-form-note">Демонстрация формы. Данные остаются в браузере. На следующем шаге можно открыть подготовленное письмо в вашей почте.</p></form><div id="ec-contact-result" hidden><p>Проверьте текст обращения. Письмо ещё не отправлено.</p><pre id="ec-request-text"></pre><a id="ec-mailto" class="button">Открыть письмо {A}</a><button class="text-link" id="ec-edit">Изменить текст</button></div></dialog><dialog class="ec-search" aria-labelledby="ec-search-title"><div class="ec-search-top"><h2 id="ec-search-title">Найти в экосистеме</h2><button class="ec-search-close" aria-label="Закрыть поиск">{icons('x')}</button></div><label class="ec-search-field">{icons('search')}<input id="ec-search-input" type="search" placeholder="Облако, защита, разработчикам…" aria-label="Поиск по страницам" autocomplete="off"></label><div id="ec-search-results" class="ec-search-results"></div><div class="ec-search-note">Поиск по страницам концепта <span>Esc — закрыть</span></div></dialog>'''
def cta(base,title='Большие идеи.<br><em>Надёжная основа.</em>'):
 return f'<section class="ec-cta wrap"><span class="eyebrow">Следующий шаг — ваш</span><h2>{title}</h2><p>Обсудим задачу. Соединим всё необходимое.</p><button class="button" data-contact>Начать разговор {A}</button><a class="text-link" href="{base}products/">Изучить продукты {icons("arrow-right")}</a></section>'
def card(p,base):
 return f'<a class="ec-product-card glow-card" href="{base}{p["slug"]}/" data-category="{p["group"]}" data-search="{p["short"]} {p["name"]} {p["brand"]} {p["group"]}"><div class="ec-card-top">{icons(p["icon"])}<span>{p["group"]}</span>{A}</div><div class="mini-sculpt mini-{p["kind"]}" aria-hidden="true"><span></span><span></span><span></span></div><h3>{p["short"]}</h3><p>{p["lead"]}</p><span class="ec-card-link">Подробнее {icons("arrow-right")}</span></a>'
def scard(s,base):
 return f'<a class="industry-card glow-card" href="{base}{s[0]}/"><div class="ec-card-top">{icons(s[4])}{A}</div><span class="eyebrow">{s[1]}</span><h3>{s[2]}</h3><p>{s[3]}</p><div class="industry-tags">'+''.join(f'<span>{P[x]["short"]}</span>' for x in s[6][:3])+'</div></a>'
def scene(kind,base,dark=False):
 mode={'compute':'cloud','cluster':'cloud','hosting':'cloud','network':'cdn','stream':'cdn','security':'security'}.get(kind,'system')
 label={'cloud':'Вычислительный модуль','cdn':'Сеть доставки контента','security':'Защитный контур','system':'Единая инфраструктура'}[mode]
 return f'''<div class="spline-stage" data-spline data-mode="{mode}"><div class="spline-viewport"><canvas aria-label="{label}. Объёмная модель инфраструктуры" tabindex="-1"></canvas></div><img class="spline-poster" src="{base}assets/spline/poster.webp?v=glow" width="1000" height="837" alt="Три объёмных модуля из серебра, тёмного металла и стекла вокруг ядра идеи"><div class="spline-loading" role="status"><span class="signal-dot"></span><span>Загрузка интерактивной модели</span></div><button class="spline-start" hidden>{icons('rotate-3d')} Исследовать в 3D</button><noscript><style>.spline-loading{{display:none}}</style><p class="spline-nojs">Облако, CDN и защита — в одной системе.</p></noscript></div>'''
def config_demo():
 return f'''<div class="config-demo" data-demo="config"><div class="console-bar"><span class="console-dots">● ● ●</span><span>Новая конфигурация</span><span class="demo-label">ПРИМЕР</span></div><div class="config-layout"><div class="config-fields"><div class="segmented" aria-label="Сценарий конфигурации"><button data-preset="start" aria-pressed="true">Старт</button><button data-preset="app" aria-pressed="false">Приложение</button><button data-preset="scale" aria-pressed="false">Масштаб</button></div><label>Вычисления <output id="cpu-out">4 vCPU</output><input type="range" min="2" max="32" step="2" value="4" name="cpu" aria-label="Количество vCPU"></label><label>Оперативная память <output id="ram-out">8 ГБ</output><input type="range" min="4" max="128" step="4" value="8" name="ram" aria-label="Оперативная память в ГБ"></label><label>SSD-диск <output id="disk-out">80 ГБ</output><input type="range" min="40" max="1000" step="20" value="80" name="disk" aria-label="SSD-диск в ГБ"></label></div><div class="config-summary"><div class="config-chip">{icons('cpu')}</div><span class="eyebrow">Ресурсы вашего проекта</span><h3 id="config-summary">4 vCPU<br><em>8 ГБ RAM</em></h3><p id="config-disk">80 ГБ SSD</p><button class="button" data-config-contact>Обсудить конфигурацию {A}</button><small>Предложение подготовит инженер</small></div></div></div>'''
def network_demo():
 return '''<div class="network-demo" data-demo="network"><div class="console-bar"><span>Маршрут контента</span><span class="demo-label">СХЕМА</span></div><div class="segmented"><button data-network="cdn" aria-pressed="true">Через CDN</button><button data-network="direct" aria-pressed="false">Напрямую</button></div><div class="route-diagram"><div class="route-origin"><i data-lucide="server"></i><b>Ваш источник</b></div><svg class="route-paths" viewBox="0 0 640 220" aria-hidden="true"><path class="path-base" d="M20 110H260Q290 110 310 60T610 35 M20 110H610 M20 110H260Q290 110 310 160T610 185"/><path class="path-flow" d="M20 110H260Q290 110 310 60T610 35 M20 110H610 M20 110H260Q290 110 310 160T610 185"/></svg><div class="route-edge"><i data-lucide="globe-2"></i><b>EdgeCDN</b><span>Контент из кэша</span></div><div class="route-users"><span><i data-lucide="smartphone"></i>Пользователь</span><span><i data-lucide="laptop"></i>Пользователь</span><span><i data-lucide="monitor"></i>Пользователь</span></div></div><p class="demo-explanation" aria-live="polite">Повторные запросы обслуживаются в сети CDN. Источник получает меньше обращений.</p></div>'''
def security_demo():
 return '''<div class="security-demo" data-demo="security"><div class="console-bar"><span>Защитный контур</span><span class="demo-label">СХЕМА</span></div><div class="segmented"><button data-protection="normal" aria-pressed="true">Обычный трафик</button><button data-protection="attack" aria-pressed="false">Во время атаки</button></div><div class="filter-visual"><div class="incoming-packets" aria-hidden="true">'''+''.join('<span class="packet"></span>' for _ in range(20))+'''</div><div class="filter-gate"><i data-lucide="shield-check"></i><b>EdgeSecurity</b></div><div class="clean-route" aria-hidden="true"></div><div class="safe-app"><i data-lucide="app-window"></i><b>Ваш продукт</b><span>Пользователи проходят</span></div></div><p class="demo-explanation" aria-live="polite">Пользовательские запросы проходят через защитный контур к приложению.</p></div>'''
def storage_demo():
 files=[('product-cover.webp','Изображения','248 КБ','image'),('launch-film.mp4','Видео','27,4 МБ','film'),('database-backup.sql','Бэкапы','128 МБ','database'),('catalog-2026.json','Данные','42 КБ','file-json'),('brand-guide.pdf','Данные','11,5 МБ','file-text')]
 return '<div class="storage-demo" data-demo="storage"><div class="console-bar"><span>project-assets /</span><span class="demo-label">ПРИМЕР БАКЕТА</span></div><div class="object-tools"><label><i data-lucide="search"></i><input type="search" placeholder="Найти объект…" aria-label="Найти объект в примере хранилища"></label><select aria-label="Тип объектов"><option>Все файлы</option><option>Изображения</option><option>Видео</option><option>Бэкапы</option><option>Данные</option></select></div><div class="object-table"><div class="object-head"><span>Имя объекта</span><span>Тип</span><span>Размер</span></div>'+''.join(f'<div class="object-row" data-object="{n}" data-type="{t}"><span>{icons(i)}{n}</span><span>{t}</span><span>{z}</span></div>' for n,t,z,i in files)+'</div><p class="object-empty" hidden>Объекты не найдены. Попробуйте другой запрос.</p><p class="demo-explanation" id="object-count" aria-live="polite">5 объектов · демонстрационные данные</p></div>'
def dns_demo():
 return '''<div class="dns-demo" data-demo="dns"><div class="console-bar"><span>example.com / DNS</span><span class="demo-label">ПРИМЕР ЗОНЫ</span></div><div class="segmented"><button data-dns="A" aria-pressed="true">A</button><button data-dns="AAAA" aria-pressed="false">AAAA</button><button data-dns="CNAME" aria-pressed="false">CNAME</button><button data-dns="MX" aria-pressed="false">MX</button></div><div class="dns-record"><div><span>Имя</span><strong id="dns-name">www</strong></div><div><span>Тип</span><strong id="dns-type">A</strong></div><div><span>Значение</span><strong id="dns-value">192.0.2.10</strong></div><div><span>TTL</span><strong>300</strong></div></div><div class="dns-code"><code id="dns-code">www.example.com. 300 IN A 192.0.2.10</code><button data-copy-dns aria-label="Скопировать пример DNS-записи"><i data-lucide="copy"></i></button></div><p class="demo-explanation" aria-live="polite">A-запись связывает имя с IPv4-адресом.</p></div>'''
def cluster_demo():
 return '''<div class="cluster-demo" data-demo="cluster"><div class="console-bar"><span>product-cluster / схема приложения</span><span class="demo-label">ПРИМЕР</span></div><div class="cluster-map"><button class="cluster-node" data-layer="ingress" aria-pressed="false"><i data-lucide="network"></i><b>Ingress</b><span>Входящий трафик</span></button><span class="cluster-wire"></span><button class="cluster-node active" data-layer="services" aria-pressed="true"><i data-lucide="boxes"></i><b>Services</b><span>Логика приложения</span></button><span class="cluster-wire"></span><button class="cluster-node" data-layer="data" aria-pressed="false"><i data-lucide="database"></i><b>Data</b><span>Хранение данных</span></button></div><p class="demo-explanation" aria-live="polite">Сервисы приложения работают в контейнерах и обмениваются данными внутри архитектуры.</p></div>'''
def qa_demo():
 return '''<div class="qa-demo" data-demo="qa"><div class="console-bar"><span>Готовность проекта</span><span class="demo-label">ПРИМЕР ЧЕК-ЛИСТА</span></div><div class="qa-progress"><span id="qa-count">0 из 4</span><div><span id="qa-bar"></span></div></div>'''+''.join(f'<label class="qa-check"><input type="checkbox"><span>{icons("check")}</span><b>{x}</b></label>' for x in ['Критические сценарии описаны','Доступы и окружения подготовлены','Проверки выполнены','Результаты согласованы'])+'<p class="demo-explanation" aria-live="polite">Отметьте выполненные этапы.</p></div>'
def demo(p,base):
 if p['demo']=='stream':return f'<div class="stream-demo"><div class="console-bar"><span>edge_center / Новый масштаб</span><span class="demo-label">ДЕМО</span></div><video controls playsinline preload="none" poster="{base}assets/intro-poster.jpg" width="1920" height="1080"><source src="{base}assets/edge-center-intro.mp4" type="video/mp4"></video><div class="stream-footer"><span>{icons("monitor-play")} Один контент. Любой экран.</span><span>00:36 / Full HD</span></div></div>'
 return {'config':config_demo,'network':network_demo,'security':security_demo,'storage':storage_demo,'dns':dns_demo,'cluster':cluster_demo,'qa':qa_demo}[p['demo']]()
def product_page(p):
 b='../';dark=' is-dark' if p.get('dark') else '';slug=p['slug']
 hero=f'''<section class="product-hero{dark}"><div class="product-top"><a href="{b}products/">{icons('arrow-left')} Все продукты</a><span>{p['brand']}</span><span class="product-edition">ИНФРАСТРУКТУРА ВОЗМОЖНОСТЕЙ / 2026</span></div><div class="product-hero-grid"><div class="product-hero-copy"><span class="eyebrow">{icons(p['icon'])}{p['name']}</span><h1>{p['hero']}</h1><p>{p['lead']}</p><div class="product-actions"><button class="button" data-contact>Обсудить подключение {A}</button><a class="text-link" href="#experience">Как это работает {icons('arrow-down')}</a></div></div>{scene(p['kind'],b,p.get('dark',False))}</div><div class="product-stats">{''.join(f'<div><strong>{n}</strong><span>{t}</span></div>' for n,t in p['stats'])}</div></section>'''
 subnav='<nav class="product-subnav" aria-label="На этой странице"><div class="wrap"><b>'+p['short']+'</b><a href="#possibilities">Возможности</a><a href="#experience">Как это работает</a><a href="#ecosystem">Экосистема</a><a href="#faq">Вопросы</a><button data-contact>Подключить '+A+'</button></div></nav>'
 features=f'''<section class="wrap section-space" id="possibilities"><div class="ec-section-heading"><span class="eyebrow">Создано для вашего продукта</span><h2>{p['statement']}</h2></div><div class="feature-bento"><article class="feature-art {'feature-art-dark' if p['art']=='security' else ''}"><img src="{b}assets/products/{p['art']}.webp" loading="lazy" alt="Материалы и слои — визуальный образ инфраструктуры" width="1920" height="1080"><div><span class="eyebrow">{p['brand']}</span><h3>Сложное внутри.<br>Простое в работе.</h3></div></article><article class="audience-card glow-card"><span class="eyebrow">Два взгляда на продукт</span><div class="segmented"><button data-audience="business" aria-pressed="true">Для бизнеса</button><button data-audience="tech" aria-pressed="false">Для инженера</button></div><div class="audience-symbol">{icons(p['icon'])}</div><h3>Важное для вас.</h3><p data-audience-copy data-business="{E(p['business'],quote=True)}" data-tech="{E(p['tech'],quote=True)}">{p['business']}</p><a href="{b}developers/" class="text-link">Инструменты команды {A}</a></article>{''.join(f'<article class="feature-card glow-card">{icons(i)}<h3>{t}</h3><p>{d}</p></article>' for i,t,d in p['features'])}</div></section>'''
 experience=f'<section class="experience-section" id="experience"><div class="wrap"><div class="ec-section-heading"><span class="eyebrow">Попробуйте взаимодействие</span><h2>{p["demoTitle"]}</h2><p>{p["demoLead"]}</p></div>{demo(p,b)}</div></section>'
 eco=f'<section class="wrap section-space" id="ecosystem"><div class="ec-section-heading split-heading"><div><span class="eyebrow">Сильнее вместе</span><h2>Соедините возможности.</h2></div><a class="text-link" href="{b}products/">Все продукты {A}</a></div><div class="ec-product-grid related-grid">'+''.join(card(P[x],b) for x in p['related'])+'</div></section>'
 faq='<section class="wrap faq-section" id="faq"><div><span class="eyebrow">Есть вопросы?</span><h2>Разберёмся<br><em>в деталях.</em></h2><a class="text-link" href="'+p.get('source','https://edgecenter.ru/'+slug)+'" target="_blank" rel="noopener">Продукт на edgecenter.ru '+A+'</a></div><div>'+''.join(f'<details><summary>{q}{icons("plus")}</summary><p>{a}</p></details>' for q,a in p['faqs'])+'</div></section>'
 return hero+subnav+features+experience+eco+faq+cta(b)
def simple_hero(eyebrow,title,desc='',extra=''):
 return f'<section class="wrap editorial-hero"><span class="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{desc}</p>{extra}</section>'
def catalog():
 filters='<div class="catalog-tools"><div class="segmented">'+''.join(f'<button data-filter="{x}" aria-pressed="{str(i==0).lower()}">{x}</button>' for i,x in enumerate(['Все продукты','Вычисления','Сеть и доставка','Безопасность','Экспертиза']))+'</div><label class="catalog-search">'+icons('search')+'<input type="search" placeholder="Найти сервис" aria-label="Поиск продуктов"></label></div>'
 return simple_hero('Экосистема EdgeЦентр','Всё для вашего<br><em>следующего шага.</em>','Десять направлений. Одна связная инфраструктура. Выберите отдельный сервис или соберите систему под свою задачу.')+f'<section class="wrap catalog-section" data-catalog>{filters}<p class="filter-result" aria-live="polite">10 продуктов</p><div class="ec-product-grid">'+''.join(card(p,'../') for p in PRODUCTS)+'</div><p class="catalog-empty" hidden>Ничего не найдено. Попробуйте другое название или категорию.</p></section>'+cta('../')
def solutions_page():return simple_hero('Решения для бизнеса','В основе<br><em>вашей индустрии.</em>','У каждого бизнеса своя нагрузка, аудитория и планы. Соединяем продукты вокруг ваших задач.')+'<section class="wrap industry-grid">'+''.join(scard(s,'../') for s in SOLUTIONS)+'</section>'+cta('../')
def industry_page(s):
 slug,name,title,lead,icon,kind,products,needs=s
 p=dict(slug=slug,name=name,brand='Решения / '+name,kind=kind,hero=title.replace('. ','<br><em>',1)+('</em>' if '. ' in title else ''),lead=lead,icon=icon,stats=[(str(i+1).zfill(2),n) for i,n in enumerate(needs)])
 hero=f'<section class="product-hero industry-hero"><div class="product-top"><a href="../solutions/">{icons("arrow-left")} Все решения</a><span>{name}</span></div><div class="product-hero-grid"><div class="product-hero-copy"><span class="eyebrow">{icons(icon)} Решения для бизнеса</span><h1>{p["hero"]}</h1><p>{lead}</p><button class="button" data-contact>Обсудить архитектуру {A}</button></div>{scene(kind,"../")}</div></section>'
 stack='<section class="wrap section-space"><div class="ec-section-heading"><span class="eyebrow">Предлагаемая архитектура</span><h2>Всё работает<br><em>на ваш сценарий.</em></h2></div><div class="architecture-flow">'+''.join(f'<a href="../{x}/">{icons(P[x]["icon"])}<span>{P[x]["short"]}</span>{icons("arrow-right")}</a>' for x in products)+'</div><div class="need-grid">'+''.join(f'<article><span>0{i+1}</span><h3>{n}</h3><p>{P[products[i]]["business"]}</p></article>' for i,n in enumerate(needs))+'</div></section>'
 return hero+stack+'<section class="experience-section"><div class="wrap"><div class="ec-section-heading"><span class="eyebrow">Продукты для отрасли</span><h2>Соберите свою систему.</h2></div><div class="ec-product-grid">'+''.join(card(P[x],'../') for x in products)+'</div></div></section>'+f'<section class="wrap migration"><span class="eyebrow">От разговора до запуска</span><h2>Пройдём этот путь вместе.</h2><ol><li><b>Разберём задачу</b><span>Нагрузка, аудитория и требования.</span></li><li><b>Спроектируем основу</b><span>Ресурсы, связность и защита.</span></li><li><b>Подготовим запуск</b><span>Перенос, проверка и сопровождение.</span></li></ol><a class="text-link" href="https://edgecenter.ru/{slug}" target="_blank" rel="noopener">Решение на edgecenter.ru {A}</a></section>'+cta('../')
def about_page():
 return simple_hero('О компании','Ближе к людям.<br><em>Сильнее в технологиях.</em>','EdgeЦентр — российский провайдер облачных и edge-решений. Даём бизнесу инфраструктуру для развития цифровых продуктов.')+'''<section class="about-mural"><img src="../assets/products/storage.webp" width="1920" height="1080" alt="Модульная архитектура из стекла и металла"><div><span class="eyebrow">Пространство для роста</span><h2>Ваши возможности.<br>Наша инфраструктура.</h2></div></section><section class="wrap company-numbers"><div><strong>70+</strong><p>точек присутствия<br>на трёх континентах</p></div><div><strong>3 000+</strong><p>физических<br>серверов</p></div><div><strong>13+<small> Тбит/с</small></strong><p>ежедневные<br>пиковые нагрузки</p></div></section><section class="wrap section-space company-story"><div><span class="eyebrow">Одна команда. Общая задача.</span><h2>Технологии,<br>которые дают<br><em>свободу создавать.</em></h2></div><div><p>Когда инфраструктура работает, команда может думать о продукте. О следующей функции, новом рынке или большой идее.</p><p>Объединяем вычисления, доставку контента, хранение и защиту. Помогаем выстроить архитектуру и поддерживаем её развитие.</p><a class="text-link" href="../contacts/">Познакомиться с командой <i data-lucide="arrow-up-right"></i></a></div></section><section class="experience-section"><div class="wrap"><div class="ec-section-heading"><span class="eyebrow">Инженерная культура</span><h2>Основа доверия.</h2></div><div class="need-grid"><article><i data-lucide="badge-check"></i><h3>Российская IT-компания</h3><p>Аккредитация Минцифры и продукты в реестре российского ПО.</p><a href="https://edgecenter.ru/registered-software" class="text-link">Зарегистрированное ПО ↗</a></article><article><i data-lucide="headset"></i><h3>Инженеры рядом</h3><p>Поддержка, которая помогает разобраться в задаче и работе сервиса.</p><a href="../contacts/" class="text-link">Связаться ↗</a></article><article><i data-lucide="file-check-2"></i><h3>Прозрачные условия</h3><p>Публичные документы, лицензии и сертификаты компании.</p><a href="https://edgecenter.ru/legal" class="text-link">Документы ↗</a></article></div></div></section>'''+cta('../')
def pricing_page():
 plans=[('Start','Для небольшого веб-проекта','4 000','1,5 ТБ','8/5 по email','2 ₽ / ГБ'),('Medium','Для растущего сервиса','8 000','5 ТБ','24/7, email и чат','1,6 ₽ / ГБ'),('Pro','Для крупных онлайн-сервисов','12 000','10 ТБ','24/7, email и чат','1,2 ₽ / ГБ'),('Enterprise','Для индивидуальной нагрузки','от 15 000','По запросу','24/7, email и чат','По запросу')]
 return simple_hero('Тарифы','Масштаб понятен.<br><em>Условия — тоже.</em>','Опубликованные пакеты CDN и индивидуальный подбор других сервисов. Выберите продукт, чтобы перейти к условиям.')+'<section class="wrap pricing-section"><div class="pricing-tabs">'+''.join(f'<a href="{("#cdn-plans" if p["slug"]=="cdn" else "../"+p["slug"]+"/")}" class="'+('active' if p['slug']=='cdn' else '')+f'">{p["short"]}</a>' for p in PRODUCTS[:8])+'</div><div class="pricing-intro" id="cdn-plans"><h2>EdgeCDN</h2><span>Помесячная оплата · цены без НДС</span></div><div class="pricing-grid">'+''.join(f'<article class="price-card {"price-featured" if i==1 else ""}"><span class="eyebrow">{n}</span><p>{d}</p><strong>{price}<small> ₽/мес.</small></strong><button class="button {"button-outline" if i!=1 else ""}" data-contact data-topic="CDN — тариф {n}">Выбрать {A}</button><ul><li>{icons("check")} {traffic} трафика</li><li>{icons("check")} Вся сеть: 70+ точек</li><li>{icons("check")} {support}</li></ul><div class="price-extra">Сверх пакета: {over}</div></article>' for i,(n,d,price,traffic,support,over) in enumerate(plans))+'</div><p class="pricing-note">Цены сверены 9 сентября 2026 года. Start, Medium и Pro включают 1 млрд запросов; дополнительные 10 000 запросов — 1,05 ₽. Для Enterprise состав пакета согласуется. Дополнительные опции оплачиваются отдельно. <a href="https://edgecenter.ru/cdn/price" target="_blank" rel="noopener">Полные актуальные условия ↗</a></p></section><section class="wrap pricing-custom"><div><span class="eyebrow">Особенная архитектура?</span><h2>Рассчитаем<br><em>под вашу задачу.</em></h2><p>Облако, выделенные серверы и комплексная защита требуют учёта конкретной нагрузки. Поможем подобрать ресурсы и условия.</p><button class="button" data-contact>Получить расчёт '+A+'</button></div><div class="pricing-sculpt"><img src="../assets/products/compute.webp" alt="Вычислительное ядро" width="1920" height="1080"></div></section>'+cta('../')
def blog_page():
 posts=[('CDN','04.09.2026','Что такое CDN и когда она нужна бизнесу','Как устроена доставка контента и какие задачи она решает.','chto-takoe-cdn','storage'),('Защита','04.09.2026','Остановить за 60 секунд','История отражения атаки с участием 300 000 ботов.','neutralized-ai-bot-army','security'),('DNS','06.07.2026','DNAME: одна запись вместо сотен','Управление целыми поддеревьями доменов.','edgecentr-zapustil-podderzhku-dname-zapisey','compute'),('Стриминг','26.06.2026','Материалы теперь рядом с видео','Раздача документов на вебинарах и онлайн-курсах.','bolshe-nikakih-ssylok-v-opisanii-kak-edgecentr-uprostil-razdachu-materialov-na-vebinarah-i-onlayn-kursah','storage'),('DNS','23.06.2026','Новый уровень доверия: DNSSEC','Криптографическая защита DNS-данных.','edgecentr-vnedril-podderzhku-dnssec','security'),('Облако','09.04.2026','Managed Kubernetes в EdgeCloud','Управляемый сервис перешёл в коммерческую эксплуатацию.','edgecentr-obyavlyaet-o-zapuske-managed-kubernetes-vysokiy-spros-podtverzhdaet-aktualnost-resheniya','compute')]
 return simple_hero('Журнал EdgeЦентр','Внутри технологий.<br><em>Ближе к практике.</em>','Новости продуктов, инженерные истории и понятные объяснения сложных вещей.')+'<section class="wrap blog-section" data-blog><div class="segmented">'+''.join(f'<button data-blog-filter="{x}" aria-pressed="{str(i==0).lower()}">{x}</button>' for i,x in enumerate(['Все','CDN','Защита','DNS','Облако','Стриминг']))+'</div><div class="blog-grid">'+''.join(f'<article class="blog-card" data-topic="{cat}"><a href="https://edgecenter.ru/blog/{url}" target="_blank" rel="noopener"><div class="blog-cover"><img src="../assets/products/{art}.webp" width="1920" height="1080" loading="lazy" alt=""><span>{cat}</span></div><div class="blog-meta">{date} <span>{cat}</span></div><h2>{title}</h2><p>{desc}</p><span class="text-link">Читать на edgecenter.ru {A}</span></a></article>' for cat,date,title,desc,url,art in posts)+'</div><p class="blog-count" aria-live="polite">6 материалов</p></section>'+cta('../')
def developers_page():
 guides=[('cloud','Облако','https://edgecenter.ru/knowledge-base/cloud/about-cloud-new'),('cdn','CDN','https://edgecenter.ru/knowledge-base/cdn/about-cdn'),('storage','Хранилище S3','https://edgecenter.ru/knowledge-base/storage/about-storage'),('dns','DNS','https://edgecenter.ru/knowledge-base/dns/about-dns'),('streaming-platform','Стриминг','https://edgecenter.ru/knowledge-base/streaming-platform/about-streaming'),('security','Веб-защита','https://edgecenter.ru/knowledge-base/web-protection/about-web-protection')]
 return simple_hero('Для разработчиков','Меньше поиска.<br><em>Больше запуска.</em>','Документация, инструкции и инструменты, чтобы соединить вашу систему с платформой EdgeЦентр.')+'''<section class="wrap developer-bento"><a class="developer-api glow-card" href="https://apidocs.edgecenter.ru/" target="_blank" rel="noopener"><span class="eyebrow">API-документация</span><h2>Инфраструктура<br>на вашем языке.</h2><div class="code-art" aria-hidden="true"><span>your_product</span><b>{</b><p>compute: <em>ready</em>,<br>network: <em>connected</em>,<br>storage: <em>available</em></p><b>}</b></div><span class="text-link">Открыть документацию ↗</span></a><div class="developer-tools"><a href="https://status.edgecenter.ru/" target="_blank" rel="noopener"><i data-lucide="activity"></i><h3>Статус сервисов</h3><p>Оперативная информация о работе платформы.</p><span>Открыть status page ↗</span></a><a href="https://lg.edgecenter.ru/" target="_blank" rel="noopener"><i data-lucide="network"></i><h3>Looking Glass</h3><p>Инструменты исследования связности сети.</p><span>Перейти к инструменту ↗</span></a></div></section><section class="wrap section-space"><div class="ec-section-heading"><span class="eyebrow">База знаний</span><h2>От первого шага<br><em>до вашей архитектуры.</em></h2></div><div class="guide-grid">'''+''.join(f'<a href="{url}" target="_blank" rel="noopener">{icons(P[slug]["icon"])}<h3>{name}</h3><p>Инструкции и настройка</p>{A}</a>' for slug,name,url in guides)+'</div></section><section class="wrap developer-help"><div><span class="eyebrow">Не нашли ответ?</span><h2>Спросите инженера.</h2><p>Поможем разобраться с подключением и работой сервисов.</p></div><a class="button" href="mailto:support@edgecenter.ru">support@edgecenter.ru '+A+'</a></section>'+cta('../')
def contacts_page():
 depts=[('Продажи','sales@edgecenter.ru','Подбор продуктов и расчёт проекта.','messages-square'),('Поддержка','support@edgecenter.ru','Вопросы по работе ваших сервисов.','headset'),('Партнёрство','partner@edgecenter.ru','Совместные продукты и возможности.','handshake'),('Карьера','hr@edgecenter.ru','Вакансии и стажировки в команде.','users'),('Пресса','pr@edgecenter.ru','Комментарии, новости и медиа.','newspaper'),('Мероприятия','events@edgecenter.ru','События и конференции.','calendar-days')]
 return simple_hero('Контакты','Технологии — наши.<br><em>Разговор — общий.</em>','Расскажите, что хотите создать. Найдём людей, которые помогут это запустить.')+'<section class="wrap contacts-lead"><a href="tel:88007750854">8 800 775 08 54 '+A+'</a><button class="button" data-contact>Обсудить проект '+A+'</button></section><section class="wrap contact-grid">'+''.join(f'<a href="mailto:{email}" class="contact-card glow-card">{icons(icon)}<h2>{name}</h2><p>{desc}</p><span>{email} {A}</span></a>' for name,email,desc,icon in depts)+'</section><section class="wrap office-block"><div><span class="eyebrow">Наш офис</span><h2>Москва</h2><p>Бизнес-центр «Авиа-Плаза»<br>ул. Авиамоторная, д. 10, корп. 2, этаж 3<br>111024, Москва, Россия</p><a class="text-link" href="https://edgecenter.ru/contacts" target="_blank" rel="noopener">Реквизиты, лицензии и сертификаты '+A+'</a></div><div class="office-art" aria-hidden="true"><div class="office-street"></div><div class="office-building">edge<span>_center</span></div><span>МОСКВА / АВИАМОТОРНАЯ</span></div></section>'+cta('../')
PAGES=[]
def write_page(slug,title,desc,body):
 base='../' if slug else './'
 three_script=f'<script type="module" src="{base}assets/spline-controller.js?v=glow"></script>' if 'data-spline' in body else ''
 page=f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="{E(desc,quote=True)}"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#132548"><meta property="og:title" content="{E(title)} — edge_center"><meta property="og:image" content="https://alexanderkozhevin.github.io/test_v2/assets/products/compute.webp"><title>{E(title)} — edge_center</title><link rel="icon" href="{base}assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="{base}assets/golos-600.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="{base}styles.css"><link rel="stylesheet" href="{base}site.css"><link rel="stylesheet" href="{base}v2.css?v=sculptures"><script src="{base}assets/lucide.min.js" defer></script><script src="{base}site.js?v=sculptures" defer></script>{three_script}</head><body data-page="{slug}" data-base="{base}">{header(base,slug)}<main id="main">{body}</main>{footer(base)}{dialogs(base)}</body></html>'''
 path=ROOT/slug/'index.html';path.parent.mkdir(exist_ok=True,parents=True);path.write_text(page)
 PAGES.append(dict(slug=slug,title=title,description=desc))
for p in PRODUCTS:write_page(p['slug'],p['name'],p['lead'],product_page(p))
for s in SOLUTIONS:write_page(s[0],s[1],s[3],industry_page(s))
for slug,title,fn in [('products','Все продукты',catalog),('solutions','Решения для бизнеса',solutions_page),('about','О компании',about_page),('pricing','Тарифы',pricing_page),('blog','Блог',blog_page),('developers','Разработчикам',developers_page),('contacts','Контакты',contacts_page)]:write_page(slug,title,'Экосистема облачных и edge-решений EdgeЦентр.',fn())
# Evolve the approved design with a Spline hero and a connected product narrative.
home=(ROOT/'src/home-original.html').read_text()
a=home.index('  <section class="hero');z=home.index('  <section class="platform',a)
hero=(ROOT/'src/v2-home.html').read_text().replace('{{SPLINE}}',scene('system','./'))
home=home[:a]+hero+home[z:]
home=home.replace('пространство для роста','инфраструктура для больших идей').replace('https://alexanderkozhevin.github.io/some_test/','https://alexanderkozhevin.github.io/test_v2/')
home=home.replace('Дайте продукту<br><span>инфраструктура для больших идей.</span>','Дайте большой идее<br><span>сильную основу.</span>')
home=home.replace('</head>','<link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="v2.css?v=sculptures"><script type="module" src="assets/spline-controller.js?v=glow"></script></head>')

a=home.index('<a class="skip"');z=home.index('<main id="main">',a);home=home[:a]+header('./')+home[z:]
a=home.index('<footer class="footer');z=home.index('<dialog class="intro-dialog',a);home=home[:a]+footer('./')+dialogs('./')+home[z:]
home=home.replace('<link rel="stylesheet" href="styles.css">','<link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="site.css">').replace('<script src="app.js" defer></script>','<script src="app.js" defer></script><script src="site.js?v=sculptures" defer></script>')
for p in PRODUCTS:
 source=p.get('source','https://edgecenter.ru/'+p['slug'])
 if p['slug']!='kubernetes':home=home.replace('href="'+source+'"','href="./'+p['slug']+'/"')
for s in SOLUTIONS:home=home.replace('href="https://edgecenter.ru/'+s[0]+'"','href="./'+s[0]+'/"')
for old,new in [('https://edgecenter.ru/about','./about/'),('https://edgecenter.ru/solutions','./solutions/'),('https://edgecenter.ru/knowledge-base','./developers/')]:home=home.replace('href="'+old+'"','href="'+new+'"')
home=home.replace('href="https://edgecenter.ru/blog/edgecentr-obyavlyaet-o-zapuske-managed-kubernetes-vysokiy-spros-podtverzhdaet-aktualnost-resheniya"','href="./kubernetes/"')
home=home.replace('<body>','<body data-page="home" data-base="./">')
# Add the catalog gateway directly after the product announcement.
home=home.replace('<section class="about', '<section class="home-explore section-wrap"><div><span class="eyebrow">Вся экосистема</span><h2>Больше возможностей<br>для вашего продукта.</h2></div><a class="button" href="./products/">Изучить 10 продуктов '+A+'</a></section><section class="about',1)
(ROOT/'index.html').write_text(home)
js=(ROOT/'src/home-original.js').read_text();a=js.index('const menuTrigger=');js=js[:a]
for p in PRODUCTS:
 orig=p.get('source','https://edgecenter.ru/'+p['slug'])
 if p['slug']=='kubernetes':orig='https://edgecenter.ru/blog/edgecentr-obyavlyaet-o-zapuske-managed-kubernetes-vysokiy-spros-podtverzhdaet-aktualnost-resheniya'
 js=js.replace("url:'"+orig+"'","url:'./"+p['slug']+"/'")
(ROOT/'app.js').write_text(js.rstrip()+'\n')
(ROOT/'site-map.json').write_text(json.dumps([dict(slug='',title='Главная',description='Инфраструктура для больших идей')]+PAGES,ensure_ascii=False,indent=2))
print(f'Built {len(PAGES)+1} static pages')
